"""Phase-2 analysis: run analysis on an enriched case and read artifacts."""
import pytest



def _run_analysis(api, case_id):
    resp = api.post(f"/api/cases/{case_id}/analyze/")
    assert resp.status_code in (200, 202), resp.content
    return resp.json()


def test_analyze_generates_artifacts(uploaded_evidence, api):
    case_id, _ = uploaded_evidence
    _run_analysis(api, case_id)
    index = api.get(f"/api/cases/{case_id}/artifacts/")
    assert index.status_code == 200


def test_artifact_before_analysis_is_unavailable(api, case):
    # No analysis run yet -> artifact loader reports 503 (not generated).
    resp = api.get(f"/api/cases/{case['case_id']}/artifacts/correlation/")
    assert resp.status_code == 503


def test_unknown_artifact_key(uploaded_evidence, api):
    case_id, _ = uploaded_evidence
    _run_analysis(api, case_id)
    resp = api.get(f"/api/cases/{case_id}/artifacts/not_a_real_key/")
    assert resp.status_code == 503


def test_analysis_artifact_roundtrip(uploaded_evidence, api):
    case_id, _ = uploaded_evidence
    _run_analysis(api, case_id)
    # At least one Phase-2 artifact should now load successfully.
    ok = 0
    for key in ("correlation", "graph", "timeline", "analytics"):
        r = api.get(f"/api/cases/{case_id}/artifacts/{key}/")
        if r.status_code == 200:
            ok += 1
    assert ok >= 1, "no Phase-2 artifact was generated by /analyze/"
