"""Report center: versioned investigation reports generated by Phase 2."""
import json

from django.http import FileResponse, HttpResponse
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.permissions import require

from .. import engine
from ..models import ActivityLog


class ReportListView(APIView):
    """Every stored report version (JSON + Markdown) for a case."""

    permission_classes = (require("report.view"),)

    def get(self, request, case_id: str):
        items = []
        for suffix, fmt in ((".json", "json"), (".md", "markdown"),
                            (".pdf", "pdf")):
            for path in engine.report_versions(case_id, suffix):
                stat = path.stat()
                generated_at = None
                if fmt == "json":
                    try:
                        generated_at = json.loads(
                            path.read_text(encoding="utf-8")
                        ).get("generated_at")
                    except (OSError, json.JSONDecodeError):
                        pass
                items.append(
                    {
                        "file_name": path.name,
                        "format": fmt,
                        "size_bytes": stat.st_size,
                        "generated_at": generated_at,
                        "modified_at": stat.st_mtime,
                    }
                )
        return Response({"case_id": case_id, "reports": items})


class ReportLatestView(APIView):
    permission_classes = (require("report.view"),)

    def get(self, request, case_id: str):
        return Response(engine.load_artifact(case_id, "report"))


class ReportDownloadView(APIView):
    permission_classes = (require("report.view"),)

    def get(self, request, case_id: str, file_name: str):
        directory = engine.investigation_config().case_dir(case_id)
        path = (directory / file_name).resolve()
        # Path traversal guard: file must stay inside the case directory.
        if directory.resolve() not in path.parents or not path.is_file():
            return Response({"detail": "Report not found."}, status=404)
        ActivityLog.record(
            username=request.user.username, module="reports",
            action="download", case_id=case_id, detail=file_name,
        )
        if path.suffix == ".md" and request.query_params.get("preview") == "1":
            return HttpResponse(
                path.read_text(encoding="utf-8"), content_type="text/markdown"
            )
        return FileResponse(open(path, "rb"), as_attachment=True, filename=file_name)
